import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Topo from "@/components/Topo";
import Capa from "@/components/Capa";
import Produtos from "@/components/Produtos";
import Sobre from "@/components/Sobre";
import Contato from "@/components/Contato";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Loja Otica visão</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Topo />
      <main>
        <Capa />
        <Produtos />
        <Sobre />
        <Contato />
      </main>
      <Footer/>
    </>
  );
}
